export {default as Home } from './Home.jsx'
export {default as About } from './About.jsx'
export {default as MyProjects} from './MyProjects'
export {default as MyResume} from './MyResume'
export {default as MyArticles} from './MyArticles'
export {default as Contact} from './Contact'